include:
  - fragments
exclude:
  - webdata
  - .bootstrap
  - bootstrap
  - .release-v212
  - final-v208.html
  - stable.html
  - app-v2-final.html
  - app-bootstrap-v206.js
  - app-data-v206-01.js
  - materialize-direct.yml
