plugins { id 'com.android.application' }

android {
    namespace 'com.bianzhifeng.hearttraining'
    compileSdk 35

    defaultConfig {
        applicationId 'com.bianzhifeng.hearttraining'
        minSdk 24
        targetSdk 35
        versionCode 202
        versionName '2.0.2'
    }

    sourceSets {
        main.assets.srcDirs = ['../../webdata']
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
